### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by fusiongyro**
This diff is large mostly because I shuffled things around and got rid of trunk and moved code to src.

The most significant change is that I have removed the old makefiles and replaced them with a single simplified, non-recursive version that makes more use of built-in rules. The only target I missed is the updatecopyright one, I think, but it bears review. This was mainly to facilitate my own understanding of how this builds, I still want to autotools-ify things. I just see this as a potentially useful stepping stone towards that goal.

I've also added some of the files autotools demands, like README, COPYING, AUTHORS, and a template ChangeLog.

### CODE REVIEW

**Comment by sanbee** [comment]
I think I should wait for a new PR from you, right?  That will have these plus other changes you have made since this PR.

**Comment by fusiongyro** [comment]
Yeah, that would probably be simplest.

**Comment by sanbee** [comment]
Just wondering where did we leave this work.  Is it basically ready to roll for non-iOS systems?

**Comment by sanbee** [comment]
I needed some mental relaxation. So merged "autoconf" branch from fusiongyro to "cleanup" branch.  I sure don't understand the autoconf build system, but if I do ./configure and then make, it gave errors related to looking for aclocal-1.15 and not finding it (on my laptop, I have aclocal-1.13).  What I figured out though is that if I run:

aclocal;automake;autoconf;./configure;make

It always works and builds the system quite beautifully!  I therefore have deleted the following files from the cleanup branch.  The rest of the code is identical to your autoconf branch.  The files below that I delete are reconstruct by aclocal, automake and autoconf:

Makefile.in
aclocal.m4
configure

I am sure these files also should be checked in, but since I don't understand their contents and how to fix them, I will wait for you to help

**Pull request merged**
